name: adchat
description: AdChat App with Agora + Firebase + Voice Messages
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ§© Core Flutter packages
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  record: ^5.1.4
  shared_preferences: ^2.3.2
  image_picker: ^1.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^19.5.0
  firebase_app_check: ^0.4.1+2


  # ðŸ”¥ Firebase core + services
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.3.0
  flutter_image_compress: ^2.1.0
  # firebase_crashlytics: ^3.0.9                        


  # ðŸŽ¥ Agora SDK for video/voice calls
  agora_rtc_engine: ^6.3.2

  # âš™ï¸ Utilities
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  swipe_to: ^1.0.5



  # ðŸ§  State management
  flutter_riverpod: ^2.4.10

  # ðŸ” Permissions (Android 14 compatible)
  permission_handler: ^12.0.1

  # âš¡ Additional dependencies
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  emoji_picker_flutter: ^4.3.0
  video_player: ^2.9.1
  country_picker: ^2.0.25
  file_picker: ^8.0.0
  flutter_secure_storage: ^10.0.0-beta.4

  # ðŸ‘¥ Modern contacts (official)
  flutter_contacts: ^1.1.9+2
  # gallery_saver_plus: ^3.2.9
  image_gallery_saver: ^2.0.3



  # ðŸ†” UUID generator (used in controllers)
  uuid: ^4.4.0
  share_plus: ^12.0.1




  # ðŸ”Š Audio player (used for message sounds)
  audioplayers: ^6.0.0
  # vibration: ^3.1.4



  # ðŸŽ¨ UI / Animation / Effects
  font_awesome_flutter: ^10.9.0
  flutter_spinkit: 5.2.2
  lottie: ^3.1.2
  animations: ^2.0.8
  cryptography: 2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/app_launcher.png
    - assets/avatar.png
    - assets/backgroundImage.png
    - assets/bg.png
    - assets/icons/
    - assets/logo/
    - assets/
    - assets/sounds/incoming_call.mp3

dependency_overrides:
  collection: 1.18.0
